version: "3.8"

services:
  mongo-ms-auth:
    image: mongo:3.6
    container_name: mongo-ms-auth
    ports:
      - "27017:27017"
    volumes:
      - mongo-auth-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - net-ms
  
  mongo-ms-order:
    image: mongo:3.6
    container_name: mongo-ms-order
    ports:
      - "27018:27017"
    volumes:
      - mongo-order-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - net-ms
  
  mongo-ms-payment:
    image: mongo:3.6
    container_name: mongo-ms-payment
    ports:
      - "27019:27017"
    volumes:
      - mongo-payment-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - net-ms

  ms-auth:
    build:
      dockerfile: ms-auth/Dockerfile
      context: .
    image: image-ms-auth
    container_name: ms-auth
    ports:
      - 8080:3000
    environment:
      - PORT=3000
      - MONGO_HOST=mongo-ms-auth
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=12345
      - MONGO_DATABASE_NAME=auth
      - MONGO_DATABASE_SOURCE=admin
      - TOKEN_TIMEOUT=15
      - TOKEN_SECRET_WORD=73e89911-5a82-428e-913e-19086d7bd2ba
    depends_on:
      - mongo-ms-auth
    restart: always
    networks:
      - net-ms

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostic -q ping
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 2s
    networks:
      - net-ms

volumes:
  mongo-auth-volume:
  mongo-order-volume:
  mongo-payment-volume:

networks:
  net-ms: