apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: ms-auth
  template:
      metadata:
        labels:
          app: ms-auth
      spec:
          containers: 
            - name: auth-container
              image: localhost:5001/image-ms-auth
              imagePullPolicy: Always
              ports:
                - containerPort: 8010
              env:
                - name: PORT
                  value: "8010"
                - name: MONGO_HOST
                  value: mongo-svc
                - name: MONGO_PORT
                  value: "27017"
                - name: MONGO_USERNAME
                  value: root
                - name: MONGO_PASSWORD
                  value: "12345"
                - name: MONGO_DATABASE_NAME
                  value: "auth"
                - name: MONGO_DATABASE_SOURCE
                  value: "admin"
                - name: TOKEN_TIMEOUT
                  value: "15"
                - name: TOKEN_SECRET_WORD
                  value: "2d7286a8-89d5-4e51-bbde-ed9f32ec5133"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: ms-auth
  ports:
    - port: 80
      targetPort: 8010
      protocol: TCP
  type: ClusterIP

