apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deploy
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: ms-delivery
  template:
    metadata:
      labels:
        app: ms-delivery
    spec:
      containers: 
        - name: delivery-container
          image: localhost:5001/image-ms-delivery
          imagePullPolicy: Always
          ports:
            - containerPort: 8040
          env:
            - name: PORT
              value: "8040"
            - name: MONGO_HOST
              value: mongo-svc
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: root
            - name: MONGO_PASSWORD
              value: "12345"
            - name: MONGO_DATABASE_NAME
              value: "delivery"
            - name: MONGO_DATABASE_SOURCE
              value: "admin"
            - name: RABBITMQ_HOST
              value: rabbitmq-svc:5672
            - name: QUEUE_ORDER_STORED_EVENT
              value: ORDER_STORED_EVENT
            - name: EXCHANGE_ORDER_COMPLETED_EVENT
              value: EXCHANGE_ORDER_COMPLETED_EVENT
            - name: EXCHANGE_ERROR_EVENT
              value: EXCHANGE_ERROR_EVENT
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-svc
spec:
  selector:
    app: ms-delivery
  ports:
    - port: 80
      targetPort: 8040
      protocol: TCP
  type: ClusterIP

