apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deploy
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: ms-payment
  template:
    metadata:
      labels:
        app: ms-payment
    spec:
          containers: 
            - name: payment-container
              image: localhost:5001/image-ms-payment
              imagePullPolicy: Always
              ports:
                - containerPort: 8030
              env:
                - name: PORT
                  value: "8030"
                - name: MONGO_HOST
                  value: mongo-svc
                - name: MONGO_PORT
                  value: "27017"
                - name: MONGO_USERNAME
                  value: root
                - name: MONGO_PASSWORD
                  value: "12345"
                - name: MONGO_DATABASE_NAME
                  value: "payment"
                - name: MONGO_DATABASE_SOURCE
                  value: "admin"
                - name: RABBITMQ_HOST
                  value: rabbitmq-svc:5672
                - name: QUEUE_ORDER_CREATED_EVENT
                  value: ORDER_CREATED_EVENT
                - name: QUEUE_ORDER_PAID_EVENT
                  value: ORDER_PAID_EVENT
                - name: EXCHANGE_ORDER_COMPLETED_EVENT
                  value: EXCHANGE_ORDER_COMPLETED_EVENT
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: ms-payment
  ports:
    - port: 80
      targetPort: 8030
      protocol: TCP
  type: ClusterIP

