apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deploy
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: ms-store
  template:
    metadata:
      labels:
        app: ms-store
    spec:
        containers: 
          - name: store-container
            image: localhost:5001/image-ms-store
            imagePullPolicy: Always
            ports:
              - containerPort: 8050
            env:
              - name: PORT
                value: "8050"
              - name: MONGO_HOST
                value: mongo-svc
              - name: MONGO_PORT
                value: "27017"
              - name: MONGO_USERNAME
                value: root
              - name: MONGO_PASSWORD
                value: "12345"
              - name: MONGO_DATABASE_NAME
                value: "store"
              - name: MONGO_DATABASE_SOURCE
                value: "admin"
              - name: RABBITMQ_HOST
                value: rabbitmq-svc:5672
              - name: QUEUE_ORDER_STORED_EVENT
                value: ORDER_STORED_EVENT
              - name: QUEUE_ORDER_PAID_EVENT
                value: ORDER_PAID_EVENT
              - name: EXCHANGE_ORDER_COMPLETED_EVENT
                value: EXCHANGE_ORDER_COMPLETED_EVENT
              - name: EXCHANGE_ERROR_EVENT
                value: EXCHANGE_ERROR_EVENT
---
apiVersion: v1
kind: Service
metadata:
  name: store-svc
spec:
  selector:
    app: ms-store
  ports:
    - port: 80
      targetPort: 8050
      protocol: TCP
  type: ClusterIP

