POST http://localhost:3000/auth/validate-access-token
Content-Type: application/json

{
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY2YTZmMTViNGQwZjcyZGVhYjZjNDUzMyIsIm5hbWUiOiJNYXJjb3MgS3V5b2MiLCJlbWFpbCI6Impta2UubWF0QGdtYWlsLmNvbSIsImlhdCI6MTcyMjI2ODUwNCwiZXhwIjoxNzIyMjY5MTA0fQ.e1w89YhBKcjeeKmWS4vY9JhCjTEnPGJ_3_436_p4q7Q"
}